from prompts.interpreter_prompts import INTERPRETER_SYSTEM_PROMPT, INTERPRETER_USER_PROMPT
from prompts.researcher_prompts import RESEARCHER_SYSTEM_PROMPT, RESEARCHER_USER_PROMPT
from prompts.solution_prompts import SOLUTION_SYSTEM_PROMPT, SOLUTION_USER_PROMPT

__all__ = [
    "INTERPRETER_SYSTEM_PROMPT",
    "INTERPRETER_USER_PROMPT",
    "RESEARCHER_SYSTEM_PROMPT",
    "RESEARCHER_USER_PROMPT",
    "SOLUTION_SYSTEM_PROMPT",
    "SOLUTION_USER_PROMPT"
]
